apiVersion: k3d.io/v1alpha5
kind: Simple

metadata:
  name: lab

servers: 1
agents: 3

registries:
  create:
    name: registry.local
    hostPort: "5000"

ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer