## Append samples of your project ##
resources:
- webapp_v1alpha1_website.yaml
# - webapp2_v1alpha1_website.yaml
- webapp_v1alpha1_postgres.yaml
- webapp_v1alpha1_backend.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
