apiVersion: webapp.lab.com/v1alpha1
kind: Website
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: frontend
spec:
  image: myapp
  replicas: 1
  host: frontend.local
